name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3'
        coverage: xdebug
    - uses: php-actions/composer@v1 # or alternative dependency management
    - name: Run php-cs-fixer
      run: ./vendor/bin/php-cs-fixer fix ./ --diff --dry-run
